# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edb530789723ed4bce258f2e115dc86f2e3573dbc7cb426741f2c4cf73b2b8b42af750ab5bd761d20e59932dc51e923d7952a9bb0da91efc3ec21df62f41227b

test:
  secret_key_base: 47c81c4380334d632e0c747e2c16ba87f9d7175a2eda628c5f4473676d5ce7443884e0ea62036e9b5a5d40a89252064db0a601691114d031e9f213b205931988

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
